"""empty message

Revision ID: bb8d506967b0
Revises: 
Create Date: 2020-10-26 19:03:03.335823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8d506967b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('cellphone', sa.String(length=12), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('otp_secret', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('Created', sa.DateTime(), nullable=True),
    sa.Column('AccountType', sa.String(length=25), nullable=True),
    sa.Column('AccountBalance', sa.Integer(), nullable=True),
    sa.Column('AccountName', sa.String(length=50), nullable=True),
    sa.Column('ownerID', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['ownerID'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_index(op.f('ix_accounts_AccountName'), 'accounts', ['AccountName'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_AccountName'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
